### ISSUE TITLE
PID-control-system uses old version of PID-controller library

### ISSUE THREAD

**Issue by hansmbakker** [ms-iot/pid-control-system#5]
@ooeygui do you know who maintains this demo?

Because https://github.com/ms-iot/pid-controller/pull/4 was merged, the library received code cleanup and was made time-dependent.

This demo application needs to be updated to make use of those changes.

**Comment by IoTGirl** [comment]
Hi Lou,
Can you please review this request?
Sincerely,
IoTGirl

**Comment by saraclay** [comment]
Hi @hansmbakker, since this issue was opened a while ago, I will close it if any recent updates have fixed this. For future issues, please file them at: www.github.com/MicrosoftDocs/windows-iotcore-docs
