### ISSUE TITLE
Code No Longer Compiles and Links

### ISSUE THREAD

**Issue by sidwarkd** [ms-iot/pid-control-system#7]
I've been trying to help several people who are interested in recreating this project but the code no longer compiles. As best as I can tell the Arduino SDK NuGet is causing compiler and linker issues. Hoping somebody internal to Microsoft could take a look and see why it no longer compiles so the community can start using the code again.

**Comment by saraclay** [comment]
Hi @sidwarkd, since this issue was opened a while ago, I will close it if any recent updates have fixed this. For future issues, please file them at: www.github.com/MicrosoftDocs/windows-iotcore-docs

**Comment by sidwarkd** [comment]
Hi @saraclay , I understand that this probably shows up on some internal report so there is a desire to close it but if the code hasn't been confirmed to compile it should be left open as it actually is an issue. I also understand that this project is no longer being actively maintained. It would be better OSS etiquette to put a disclaimer in the README that the project is no longer active and therefore issues will not be resolved or investigated by Microsoft. However, if a community member would like to contribute it would be good for them to know what active issues actually exist on this project. Please consider leaving this open or verify that it is actually resolved.
